### PR TITLE
Add documentation for ExpressionBodySyntax

### PR DESCRIPTION
**Pull request by rainerkern**
Hi,
I am a first time contributor and would like to add this documentation snippet for the ExpressionBodySyntax tool.
cheers
Rainer

### CODE REVIEW

**Comment by rtfpessoa** [comment]
We are currently using `rule.getIssue.getDescription` from the detekt library. If we could get an extended description directly from them would be really nice.

**Comment by rtfpessoa** [comment]
Also can you amend this commit for CircleCI to trigger the build.

**Comment by rainerkern** [comment]
Hi @rtfpessoa,
thanks for the answer but i am sorry i am kind of lost.
I am really happy to contribute - and probably will contribute to other Kotlin related stuff as well.
I just need the a file that I can edit.

if you can point me to that I think i will be good and able to push another version to the pull request.
cheers
Rainer

**Comment by rtfpessoa** [comment]
@rainerkern I asked in the detekt repo how to proceed. https://github.com/arturbosch/detekt/issues/923

In the meanwhile if you can amend this PR for CircleCI to start the build we can merge this while we get a more definitive solution.

**Comment by rtfpessoa** [comment]
@rainerkern as @arturbosch said it would be nice if you could also add this docs in the official KDocs.

I just did an implementation in #10 that reads them.

Also in the meanwhile if you can amend this PR for CircleCI to start the build we can merge this while we get definitive solution merged.

**Comment by rainerkern** [comment]
Good Morning @rtfpessoa and @arturbosch 
Thanks for your answers,
I checked the official documentation and found that my description already exists there
https://github.com/arturbosch/detekt/blob/master/docs/pages/documentation/style.md#expressionbodysyntax

@rtfpessoa I have one more question ... you wrote "amend this PR for CircleCI" but I honestly do not understand what you mean.
I know how to amend a commit in GIT, i know what CircleCI is, but i do not know how to amend something "for CircleCI".

But anyway since the official Detekt docu already contains a snippet for ExpressionBody AND you are already creating a permanent solution, I suggest to close this PR and I will just add any further documentation that I have directly to the Detekt repository.
Do you agree?

best regards
Rainer

**Comment by rtfpessoa** [comment]
That make sense. The new docs will be deployed soon.

**Pull request closed without merging**
